# OpenAI Taxi v2

## State 0: Importing Dependencies

In [1]:
import numpy as np
import gym
import random

## State 1: Create Environment

In [2]:
env = gym.make("Taxi-v2")
env.render()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



## State 2: Create the Q-table and initialize it

In [10]:
action_space = env.action_space.n
print("Action space's size: ", action_size)

state_space = env.observation_space.n
print("State space's size: ", state_space)

Action space's size:  6
State space's size:  500


In [11]:
qtable = np.zeros((state_space, action_space))
print(qtable)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


## State 3: Create Hyperparameters

In [ ]:
total_episodes = 50000
total_test_episodes = 100
max_steps = 99

learning_rate = 0.7
gamma = 0.618

epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.01

## State 4: Q-learning Algorithm

In [ ]:
for episode in range(total_episodes):
    #Reset environment in the beginning of each episode
    state = env.reset()
    step = 0
    done = False
    
    for step in range(max_steps):
        #Exploration and exploitation tradeoff
        exp_exp_tradeoff = random.uniform(0, 1)
        
        #Exploitation if number is greater than epsilon
        if exp_exp_tradeoff > epsilon:
            #Look in Q-table
            action = np.argmax(qtable[state, :])
    